version: '3.9'

services:
  app:
    container_name: praxis-chat
    build:
      context: .
      target: runtime_stage
      args:
        - NODE_ENV=${NODE_ENV}
        - VITE_SERVER_PORT=${VITE_SERVER_PORT}
        - DB_MIGRATIONS=${DB_MIGRATIONS}
    volumes:
      - content:/app/dist/content
    ports:
      - ${VITE_SERVER_PORT}:${VITE_SERVER_PORT}
    restart: always
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:18.1
    command: ['postgres', '-c', 'port=${DB_PORT}']
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -p ${DB_PORT}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql

  cache:
    container_name: cache
    image: redis:8.4.0
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'redis-cli -p ${REDIS_PORT} -a ${REDIS_PASSWORD} ping | grep PONG',
        ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --port ${REDIS_PORT} --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    env_file: .env
    volumes:
      - cache:/data

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    profiles: ['ollama']
    ports:
      - ${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}
    volumes:
      - ollama:/root/.ollama
    restart: always
    env_file: .env

volumes:
  pgdata:
  content:
  cache:
    driver: local
  ollama:
