services:
  database:
    image: postgres:18.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '55432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5432']
      interval: 2s
      timeout: 5s
      retries: 30

  cache:
    image: redis:8.4.0
    command: redis-server --save "" --appendonly no --loglevel warning --requirepass redis
    ports:
      - '56379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -p 6379 -a redis ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 30
